### ISSUE TITLE
support bilingual Cambridge dictionary

### ISSUE THREAD

**Issue by omega3** [am-silex/anki_cambridge#1]
Can you support bilingual Cambridge dictionary:
https://dictionary.cambridge.org/dictionary/english-polish/become

Click on three dots to choose language:
https://i.imgur.com/kDuGTRc.png 

By the way, can you describe how to use it or create a video, please? I paste this sample link but nothing happens. How to get these cookies?

**Comment by am-silex** [comment]
Hi.
I've updated description - see Readme.md for quick visual guides
