### ISSUE TITLE
Fetching fails

### ISSUE THREAD

**Issue by geff10** [am-silex/anki_cambridge#12]
I'm currently logged into Cambridge Dictionary with Google, set copied and pasted the cookie content, but fetching my wordlist does not work.
It says: "Fetching failed:
Authentification failed. Either your cookie expired or your are trying to delete entries from a community wordlist."

**Comment by omega3** [comment]
It may depend on what browser you use.

Have you tried this:

To get cookies in Firefox: log in to your Cambridge account, search for word, press F12, tab Network, click on dictionary Cambridge line, on the right you will see cookies. Copy the entire line and paste to add-on.
https://i.imgur.com/sOByVAZ.png

Also check if creating an account makes any difference.

**Comment by am-silex** [comment]
Hi
It seams like you are trying to save words from community word list - so you can't remove it after fetching. Use your own word list

**Comment by geff10** [comment]
Hi, that's the thing: I used my own word list. I didn't try to remove anything, I just tried to fetch the word list.

**Comment by omega3** [comment]
Maybe create new test profile in the latest Anki stable version and recheck.

**Comment by am-silex** [comment]
> Hi, that's the thing: I used my own word list. I didn't try to remove anything, I just tried to fetch the word list.

Removing fetched entries is a feature. Otherwise you'll end up with a lot of duplicate note in Anki.
Maybe it's a good idea to let a user decide whether to remove after fetching or not but right now it isn't possible.
