### ISSUE TITLE
Audio files contain only first word in phrasal verbs case

### ISSUE THREAD

**Issue by glebmark** [am-silex/anki_cambridge#16]
When you add English phrasal verbs such as "come along, go for, go out" and etc. audio files contain only first word.
For example, when I add "come along" by https://dictionary.cambridge.org/dictionary/english/come-along it's add audio records (both UK and US) with just one word - "come", but "come along" is expected.

**Comment by am-silex** [comment]
Hello
I've noticed the same issue with Cambridge dictionary a long ago. Unfortunately it's a feature of the dictionary rather than issue with addon - most phrasal verbs only have sounds of the base verb
