### ISSUE TITLE
Import verb's parts as separate cards

### ISSUE THREAD

**Issue by fedy2** [am-silex/anki_cambridge#19]
Maybe out of scope for this add-on, but would be nice to import the verb's parts as separate cards.

For example, the verb [throw](https://dictionary.cambridge.org/dictionary/english/throw) has: **throw** (base form/infinitive), **threw** (past simple) and **thrown** (past participle).

The add-on can create:
a. a card with the three parts as answer.
b. a card for each part.

The user can configure which one to use.

**Comment by am-silex** [comment]
You're talking about a card type for irregular verbs. It's possible as a different deck, as in a deck there is only one type (if I remember correctly).

**Comment by fedy2** [comment]
The add-on can create a new Cambridge - irregular verbs deck and add the new cards there.
