### ISSUE TITLE
Enable import of words with links from specific dictionaries

### ISSUE THREAD

**Issue by fedy2** [am-silex/anki_cambridge#20]
The add-on fails to import a word with a link from a specific dictionary.
For example, the import of word `drop` from the Learner's dictionary via link https://dictionary.cambridge.org/dictionary/learner-english/drop, fails without showing a dialog.

**Comment by am-silex** [comment]
Most probably, different dictionaries are structured differently in terms of DOM. It might be possible to adjust the downloader module to accommodate it for the most used ones, but, unfortunately, I don't have time for that improvement at the moment.
