### ISSUE TITLE
Import doesn't work when the word contains only one definition

### ISSUE THREAD

**Issue by fedy2** [am-silex/anki_cambridge#21]
Steps to reproduce:
1. start new import (CTRL + L)
2. past link https://dictionary.cambridge.org/dictionary/english/confident
3. click OK
4. the add-on shows the import dialog:
![Screenshot from 2022-09-19 17-33-18](https://user-images.githubusercontent.com/1282491/191067605-038365f4-7d9e-43d3-a844-70c213b51369.png)
5. Check the only definition available
6. Click OK

What happens? Nothing.
What so you expect to happen? 
1. Creation of card for word `confident`
2. Dialog to hide.

Note: Probably triggered by this issue, the title of the import dialog is not updated.

**Comment by am-silex** [comment]
Fixed
