### ISSUE TITLE
OK and Cancel buttons not visible with word with multiple definitions

### ISSUE THREAD

**Issue by fedy2** [am-silex/anki_cambridge#23]
The "Ok" and "Cancel" buttons are not visible when the word to import has a high number of definitions:
![Screenshot from 2022-09-24 09-59-15](https://user-images.githubusercontent.com/1282491/192089678-d6b83716-789a-4b37-ac66-24475893c888.png)

For example, with the word `bound`: https://dictionary.cambridge.org/dictionary/english/bound

**Comment by am-silex** [comment]
Closed in this [pull](https://github.com/am-silex/anki_cambridge/pull/24)
