### ISSUE TITLE
cannot Authorize via Google

### ISSUE THREAD

**Issue by YELLOWHOMEIN** [am-silex/anki_cambridge#25]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/27610409/221220964-23a068b1-5cc8-4935-9660-d6ed121df3ea.png">

<img width="659" alt="image" src="https://user-images.githubusercontent.com/27610409/221221093-29ff8ca6-ec94-43f1-9065-e7d8bc0ecfc3.png">

My laptop is MacBook pro, and I can not authorize via Google

**Comment by YELLOWHOMEIN** [comment]
when I click google, the page is blank

**Comment by am-silex** [comment]
Hi
It seems to me some authorization issue with provider - whichever Cambridge Dictionary is hooked up to and it's not related to this addon (at least at this step)

**Comment by YELLOWHOMEIN** [comment]
Fetching failed:
Authentification failed. Either your cookie expired or your are trying to delete entries from a community wordlist.

I don't know which cookie's value should I copy. Can you provide more specific instructions? Thanks. I think many people like  me will trapped in this step.

**Comment by YELLOWHOMEIN** [comment]
this instruction was fine
https://www.jianshu.com/p/5aab0a57a1d1

**Comment by YELLOWHOMEIN** [comment]
Can we add many words at once to the Cambridge dictionary? It seems that now we can only add words to wordlist one by one？
