### ISSUE TITLE
Fetch from wordlist doesn't work

### ISSUE THREAD

**Issue by omega3** [am-silex/anki_cambridge#5]
Forbidden.
https://i.imgur.com/vnaGWOm.png

https://i.imgur.com/wlWvec5.png

**Comment by am-silex** [comment]
Hi
Is it your wordlist? If not you are bound to catch this error because after creating a note addon tries to delete wordlist entry

**Comment by omega3** [comment]
Yes. It is my wordlist. I had cookies from Chromium but I was logged in in Firefox. Does it matter? Is it necessary to be logged in to Cambridge account when fetching wordlist?

**Comment by am-silex** [comment]
Did it create any notes before throwing error?

**Comment by omega3** [comment]
No.
Do I need to paste also _gid= in cookies field?

**Comment by am-silex** [comment]
Just updated add-on on Anki website and checked - worked like dream.
Yes, you need to paste the whole cookie
