### ISSUE TITLE
Please make it possible to use bilingual dictionaries

### ISSUE THREAD

**Issue by omega3** [am-silex/anki_cambridge#6]
Please make it possible to use bilingual dictionaries:
https://i.imgur.com/TBofr6c.png

It creates new notes from link:
https://dictionary.cambridge.org/dictionary/english/become

but not from:
https://dictionary.cambridge.org/pl/dictionary/english-polish/become

**Comment by am-silex** [comment]
Tags for bilingual dictionaries haven't been explored yet. Furthermore, creating notes with this support hasn't been implemented. Maybe in the future
