### ISSUE TITLE
sound icons and a picture

### ISSUE THREAD

**Issue by omega3** [am-silex/anki_cambridge#7]
It is strange because in other decks I don't have it but with this one when I preview I see sound icons and a funny car picture:

https://i.imgur.com/sM2gfc6.png

https://i.imgur.com/HLuAwDQ.png

Is it somewhere in template? I can't see it?

Is it save to remove Picture field from note type?

**Comment by am-silex** [comment]
That's really strange - the picture and sound are right in the note preview as it should be
https://c2n.me/47tGiuY
This fields are part of Cambridge note type - you can change template to hide or rearrange the fields on a card but definitely mustn't be removed any of them as they reference in code when filling.

**Comment by omega3** [comment]
Ok. The icons were from mpv. This was probably some jung in my media collection. 
https://i.imgur.com/ph4eH4q.png

I removed these png from media folder.
I think you close this issue.

**Comment by am-silex** [comment]
Ok
