### ISSUE TITLE
 Links guide does not work.

### ISSUE THREAD

**Issue by A-K12** [am-silex/anki_cambridge#9]
Links in the file "Readme.md" does not work correctly.
The website clip2net.com restricted access to data. Only paid clients can view the data.
![Screenshot_2](https://user-images.githubusercontent.com/37290322/86507792-905e7200-bdf4-11ea-8f34-23b0b3de121d.jpg)

**Comment by am-silex** [comment]
Re-uploaded images on another hosting.
